name: AOM Organization

on:
  pull_request:
    branches: 
     - main
jobs:
  check-application:  
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['5.0.x' ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Where we are    
        run: pwd
      - name: list some key files
        run: ls -lrt
      - name: Install dependencies
        run: dotnet restore ./AOM.StudentManager/
      - name: Build
        run: dotnet build --no-restore ./AOM.StudentManager/      
    
