name: AOM Organization

on:
  push:
    branches: 
     - main
jobs:
  check-application:  
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['5.0.x' ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Where we are    
        run: pwd
      - name: list some key files
        run: ls -lrt
      - name: Install dependencies
        run: dotnet restore 
      - name: Build
        run: dotnet build --no-restore
      
      - name: Set up QEMU        
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:          
          push: false
          tags: adhan2604/aomapi:latest       
          context: ./src/API
          
    
